language: ruby
rvm:
  - '2.1'
  - '2.2'


gemfile:
  - Gemfile

matrix:

after_success:
  - ruby benchmarks/bench.rb

notifications:
  email: false


addons:
  codeclimate:
    repo_token: 71237749c90394bd3625b66744eaa59ff237b291cef608fba8d11474fe9e8a5b
